// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tier3.DataAccess;

namespace Tier3.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20211213105110_Final")]
    partial class Final
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Tier3.Models.Bill.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bill")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    
                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Bill");
                });
            
            modelBuilder.Entity("Tier3.Models.Client.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");
                    
                    b.Property<string>("Phonenumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Tier3.Models.Bills", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClientId", "BillId");

                    b.HasIndex("BillId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Tier3.Models.Manager.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manager");
                });
            
            

            modelBuilder.Entity("Tier3.Models.ClientBurial", b =>
                {
                    b.HasOne("Tier3.Models.Burial.Burial", "BurialClient")
                        .WithMany("ClientBurials")
                        .HasForeignKey("BurialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tier3.Models.Client.Client", "Client")
                        .WithMany("ClientBurials")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BurialClient");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Tier3.Models.Preference.Preference", b =>
                {
                    b.HasOne("Tier3.Models.Burial.Burial", null)
                        .WithMany("PreferenceForBurial")
                        .HasForeignKey("BurialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tier3.Models.Burial.Burial", b =>
                {
                    b.Navigation("BurialPreferences");

                    b.Navigation("ClientBurials");

                    b.Navigation("PreferenceForBurial");
                });

            modelBuilder.Entity("Tier3.Models.Client.Client", b =>
                {
                    b.Navigation("Burials");

                    b.Navigation("ClientBurials");
                });

            modelBuilder.Entity("Tier3.Models.Preference.Preference", b =>
                {
                    b.Navigation("BurialPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
