namespace Db3.Utility;

public enum NetworkType
{
    REGISTER,
    LOGIN,
    BILLS,
    DELETECLIENT,
    GETCLIENTBYUSERNAME,
    GETCLIENTBYID,
    DELETEBILL,
    DELETEBILLBYID,
    ADDBILL,
    DELETEMANAGER,
    LOGINMANAGER,
    GETMANAGERBYID,
    GETMANAGERBYUSERNAME,
    CONNECTION,
    SUBTOWATER,
    SUBTOELECTRICITY,
    SUBTOHEATING,
    SUBTORENT,
    UNSUBSCRIBE
}